website/sleep/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from . import views


app_name ='sleep'

urlpatterns = [
    url(r'^graph/(?P<id>[0-9]+)/$', views.graph, name='graph'),
    url(r'^stop/$', views.stopGraph, name='stopGraph'),
    url(r'^ip/$', views.ipHandling.as_view(), name='ip'),
    url(r'^$', views.base, name='home')
]

website/website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts.views import (login_view, logout_view, register_view)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^register/', register_view, name='register'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^', include('sleep.urls')),

]

website/accounts/models.py
from django.db import models

# Create your models here.

website/sensorEmulator/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

website/sleep/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class GraphDataPoints(models.Model):
    user = models.ForeignKey(User, unique=True)
    yVal = models.IntegerField()

website/accounts/forms.py
from django import forms
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout,
    )

User = get_user_model()

class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("This user does not exist")
            if not user.check_password(password):
                raise forms.ValidationError("Incorrect password")
            if not user.is_active:
                raise forms.ValidationError("This user is not longer active.")
        return super(UserLoginForm, self).clean()

class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, label='Password')
    password2 = forms.CharField(widget=forms.PasswordInput, label='Confirm Password')
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'password',
            'password2',
        ]

    def clean_password2(self):
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password != password2:
            raise forms.ValidationError("Password must match")
        return password

website/sleep/forms.py
from django.contrib.auth.models import User
from django import forms

#ipform
class ipForm(forms.Form):
    ip_address = forms.CharField(max_length=200)

website/accounts/views.py
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout,
    )

from django.shortcuts import render, redirect
from .forms import UserLoginForm, UserRegisterForm

# Create your views here.

def login_view(request):
    print(request.user.is_authenticated())
    title = "Login"
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect("/")
        print(request.user.is_authenticated())

    return render(request, "form.html", {"form":form, "title":title})


def register_view(request):
    title = "Register"
    form = UserRegisterForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        password = form.cleaned_data.get('password')
        user.set_password(password)
        user.save()
        new_user = authenticate(username=user.username, password=password)
        login(request, user)
        return redirect("/")

    context = {
        "form": form,
        "title": title
    }
    return render(request, "form.html", {"form":form, "title":title})


def logout_view(request):
    logout(request)
    return redirect("/")

website/sensorEmulator/views.py
from django.shortcuts import render

# Create your views here.

website/sleep/views.py
from django.shortcuts import render,redirect,HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from .forms import ipForm
from .pleasework import start,stop,ping
from django.core.validators import validate_ipv46_address
from django.core.exceptions import ValidationError

from django.contrib.sessions.backends.db import SessionStore

#from netaddr import *

from random import randint


def base(request):
    return render(request, 'index.html')

def graph(request, id):
    print(id, "url-id")
    return render(request, 'graph.html')

class ipHandling(View):
    template_name = 'ipaddress.html'
    form_class = ipForm
    #blank form
    def get(self,request):
        form = self.form_class(None)
        return render(request,self.template_name,{'form':form})


    def post(self, request):
        form = self.form_class(request.POST)
        ip = request.POST["ip_address"]
        if form.is_valid():
            #validate_ipv46_address(ip)
            channel_id = str(randint(1,1000))
            start(ip, channel_id)
            #start session with id based on ip->id conversion
            #ses_id = str(int(netaddr.IPAddress(ip)))
            # s = SessionStore()
            # ses_id = str(40)
            # s['session_id'] = ses_id
            # s.create()
            #request.session['session_id'] = ses_id
            #print(ses_id, "sesid")
            return redirect('sleep:graph', id=channel_id)

        return render(request, self.template_name, {'form':form})


def stopGraph(request):
    stop()
    return redirect('/')

website/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

website/accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

website/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Welcome</h1>
    <p>
        You can log in here!
    </p>
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
</div>
{% endblock %}

website/accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Logged out</h1>
    <p>
        You have logged out!
    </p>
</div>
{% endblock %}

website/accounts/templates/accounts/profile.html
{% extends 'base.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1>Profile</h1>
    <p>Username: {{ user }}</p>
    <p>First name: {{ user.first_name }}</p>
    <p>Last name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Description: {{ user.userprofile.description }}</p>
    <p>Phone: {{ user.userprofile.phone }}</p>
    <p>City: {{ user.userprofile.city }}</p>
    <p>Website: {{ user.userprofile.website }}</p>
    <img src="{{ user.userprofile.image.url }}" width="240">
</div>

{% endblock %}

website/accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>
{% endblock %}

website/accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset</h1>
    <p>
        Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
</div>
{% endblock %}

website/accounts/templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset complete</h1>
    <a href="{% url 'accounts:login' %}">Log in</a>
</div>
{% endblock %}

website/accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Enter new password</h1>
    <p>

    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
</div>
{% endblock %}

website/accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset sent</h1>
    <p>
        We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

        If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.
    </p>
</div>
{% endblock %}

website/accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

website/accounts/templates/base.html
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% block head %}
        <title>Base</title>
        {% endblock %}
    </head>
    <body>
        <br>
        <div class="container">
            <nav class="navbar navbar-default">
            <div class="container-fluid">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Social Network</a>
              </div>
              <div id="navbar" class="navbar-collapse collapse">
                {% if user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home:home' %}">Home</a></li>
                    <li><a href="{% url 'accounts:view_profile' %}">Profile</a></li>
                    <li><a href="{% url 'accounts:edit_profile' %}">Edit Profile</a></li>
                    <li><a href="{% url 'accounts:change_password' %}">Change Password</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
                </ul>
                {% else %}
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'accounts:reset_password' %}">Reset Password</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li><a href="{% url 'accounts:login' %}">Login</a></li>
                  <li><a href="{% url 'accounts:register' %}">Register</a></li>
                </ul>
                {% endif %}
              </div><!--/.nav-collapse -->
            </div><!--/.container-fluid -->
          </nav>
        </div>
        {% block body %}
            <h1>Base</h1>
        {% endblock %}
    </body>
    <script
      src="https://code.jquery.com/jquery-3.1.1.min.js"
      integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
      crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>

website/accounts/templates/form.html
<!--{% load crispy_forms_tags %}-->

{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
    <h1>{{ title }}</h1>
    <hr/>

    <form method='POST' actions='' enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-default" value="{{ title }}" />
    </form>
</div>
{% endblock content %}

website/sleep/templates/form.html
{% extends "header.html" %}

{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
    <h1>{{ title }}</h1>
    <hr/>

    <form method='POST' actions='' enctype='multipart/form-data'>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-default" value="{{ title }}" />
    </form>
</div>
{% endblock content %}

website/sleep/templates/graph.html
{% extends "header.html" %}

{% block content %}
<script type="text/javascript">
window.onload = function () {
  var dataPoints = [];
  var datalength = 20;
  var chart = new CanvasJS.Chart("chartContainer",
  {
    zoomEnabled: true,
    panEnabled: true,

    title:{
      text: "Data Tracker"
    },

    axisX:{
        title: "Time(seconds)"
    },
    data : [{
      type  : "spline",
      dataPoints : dataPoints

      }]

    });
  chart.render();

  xVal = 0;
  var updateChart = function(senseValue){
    console.log(senseValue + " Sense value");

    yVal = senseValue;
    i = 0;
    for(i; i<dataPoints.length;i++){
      console.log(dataPoints[i].y + " dp");
    }
    console.log(dataPoints);
    dataPoints.push({
      x : xVal,
      y : yVal
    });
    xVal = xVal +1;
    if(dataPoints.length > datalength){
      dataPoints.shift();
    }
    chart.render();

  };

  $(function () {
    var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
    //var ws_path = ws_scheme + '://' + window.location.host + "/values/";                           //+window.location.pathname + "stream/"
    var ws_path = ws_scheme + '://' + window.location.host  + window.location.pathname + "values/"
    console.log("Connecting to " + ws_path);
    var socket = new ReconnectingWebSocket(ws_path);

    socket.onmessage = function(message){
      console.log("Got message " + message.data);
      var sensdata = JSON.parse(message.data);
      document.getElementById("value").innerHTML = "Sensor value: " + message.data;

      updateChart(sensdata);
    };

  });

}

</script>


<p id="value"></p>
<div id="chartContainer" style="height: 300px; width: 100%;">
</div>
<a href="{% url 'sleep:stopGraph' %}"><button type="button" class="btn btn-danger">Stop</button></a>

{% endblock %}

website/sleep/templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %} Beddit-Sleep tracker {% endblock %}</title>
  <!-- Loads the path to your static files -->
  {% load staticfiles %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
   integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" type="text/css" href="{% static 'sleep/css/style.css' %}"/>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="{% static 'sleep/js/canvasjs.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'sleep/js/jquery-1.12.2.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'sleep/js/reconnecting-websocket.min.js' %}"></script>

</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="/" class="navbar-brand">Data Trackers</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">



          <ul class="nav navbar-nav navbar-right">
            <li class="">
              <a href="">
                History
              </a>
            </li>
            <li class="">
              <a href="/ip/">
                Enter IP
              </a>
            </li>
            {% if not request.user.is_authenticated %}
            <li class="">
              <a href="/login">
                <span class="glyphicon glyphicon-log-in"></span>&nbsp; Login
              </a>
            </li>
              <li class="">
              <a href="/register">
                <span class="glyphicon glyphicon-pencil"></span>&nbsp; Register
              </a>
            </li>
            {% else %}
            <li class="">
              <a href="/logout">
                <span class="glyphicon glyphicon-log-out"></span>&nbsp; Logout
              </a>
            </li>
            {% endif %}
          </ul>

        </div>
    </div>
  </nav>
  {% block content %}
    <p> {{context}} </p>
  {% endblock %}
</body>
</html>

website/sleep/templates/index.html
{% extends "header.html" %}

{% block content %}
<script type="text/javascript">
window.onload = function () {
  var dataPoints = [];
  var chart = new CanvasJS.Chart("chartContainer",
  {
    zoomEnabled: true,
    panEnabled: true,
    title:{
      text: "Data Tracker"
    },
    data : [{
      type  : "spline",
      dataPoints : dataPoints
      }]

    });
  chart.render();

  var updateChart = function(senseValue){
    console.log(senseValue + " Sense value");
    yVal = senseValue;
    i = 0
    for(i; i<dataPoints.length;i++){
      console.log(dataPoints[i].y + " dp");
    }
    console.log(dataPoints);
    dataPoints.push({
      y : yVal
    });
    chart.render();

  };

  $(function () {
    var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
    var ws_path = ws_scheme + '://' + window.location.host + "/values/";                           //+window.location.pathname + "stream/"
    console.log("Connecting to " + ws_path);
    var socket = new ReconnectingWebSocket(ws_path);

    socket.onmessage = function(message){
      console.log("Got message " + message.data);
      var sensdata = JSON.parse(message.data);
      document.getElementById("value").innerHTML = "Sensor value: " + message.data;

      updateChart(sensdata);
    };

  });

  var yVal = 0;

}

</script>

<h3 style="text-align: center">Welcome to Beddit sleep tracker.</h3>
<p style="text-align: center">We are 5 student who have worked on a web app that displays real time sleep tracking data from a beddit sensor.</p>
<p id="value"></p>

<div id="chartContainer" style="height: 300px; width: 100%;">
</div>
{% endblock %}

website/sleep/templates/ipaddress.html
{% extends "header.html" %}
{% block title %} Django4lyf {% endblock %}

{% block content %}
    <h3> Enter IP-address of client </h3> <br>

    <form class="form-vertical" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Connect" name="ipaddress">
    </form>
{% endblock %}